### ISSUE TITLE
Release new version of ECS.NET 8.6.0

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/ecs-dotnet#197]
- [x] sanity check [the process field set](https://www.elastic.co/guide/en/ecs/current/ecs-process.html) (@gregkalapos)
- [x] Extend the code generator to include richer meta information in xml documentation. (@Mpdreamz )
- [x] Merge https://github.com/elastic/ecs-dotnet/pull/110 as it has a lot of integration tests using the new types. (@gregkalapos)
- [x] We will aim for an `8.4.0-alpha` first to validate our build tooling. (@mpdreamz)
- [x] Include direct support for ECS fields in message templates (@mpdreamz) https://github.com/elastic/ecs-dotnet/pull/229
- [x] Utilize `labels` for value types and `metadata` for objects. (@Mpdreamz) https://github.com/elastic/ecs-dotnet/pull/229
- [x] Do not assume we can safely serialize to `metadata` #219 (@Mpdreamz)
- [x] Bump to 8.5/8.6 if that bump is not complicated, prioritize releasing (@Mpdreamz)
- [x] Breaking changes documentation. Include an paragraph describing what's expected to break with this new major version and why. (@mpdreamz)

**Comment by bonyaroslav** [comment]
@Mpdreamz @gregkalapos  Any news when we can use it? We're waiting for many months already

**Comment by odin568** [comment]
Same for me. Eager to use updated version to get rid of some workarounds

**Comment by lewinskimaciej** [comment]
Is this package still being maintained? We desperately need https://github.com/elastic/ecs-dotnet/issues/167 but it seems that there hasn't been a release in 1,5 years. Is there something we can do to help push this out?

**Comment by Mpdreamz** [comment]
Still maintained folks! Thanks for the nudges for an update. 

I have been on leave for an extended period of time but am back working on getting an update out the door. Any feedback on the upcoming pre-release would be most welcomed! 

Will comment on right here when it goes up on nuget.

**Comment by Mpdreamz** [comment]
https://github.com/elastic/ecs-dotnet/compare/1.6...e8086da081a16518160c47ca06caa209f67caa4a

**Comment by Mpdreamz** [comment]
Heads up here that we just shipped version `8.4.0-alpha1` to nuget. 

I intend to wait two weeks to collect feedback on this new version before shipping it as a GA release (`8.4.0`). 

A LOT of changes have gone in since we last release `1.6.0-alpha1`, you can see the [full list of changes here](https://github.com/elastic/ecs-dotnet/compare/1.6...e8086da081a16518160c47ca06caa209f67caa4a)

Here are *some* highlights:

New integrations

* [`Elasticsearch.Extensions.Logging`](https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/8.4.0-alpha1#readme-body-tab) an integration with `Microsoft.Extensions.Logging` that writes logs directly to Elasticsearch or Elastic Cloud (thank you @sgryphon for all the help)
* [`Elastic.CommonSchema.Serilog.Sink`](https://www.nuget.org/packages/Elastic.CommonSchema.Serilog.Sink/8.4.0-alpha1#readme-body-tab) a Serilog sink that writes ecs logs directly to Elasticsearch or Elastic Cloud
* [`Elastic.CommonSchema.Log4Net`](https://www.nuget.org/packages/Elastic.CommonSchema.Log4net/8.4.0-alpha1#readme-body-tab) Log4Net integration that logs to files in ecs-logging format. (thank you @andreycha!)
* [`Elastic.Ingest.Elasticsearch.CommonSchema`](https://www.nuget.org/packages/Elastic.Ingest.Elasticsearch.CommonSchema/8.4.0-alpha1) a specialization of `Elastic.Ingest.Elasticsearch` to push data to datastreams indices that is fully ECS aware and can bootstrap the target datastreams/indices confirming ECS mappings.


Big Updates:
* Completely rewrote the code generator from scratch to accomodate the ECS spec format changes since 1.6 to 8.x. 
* Spun off the ingest components into their own seperate libraries: [elastic/elastic-ingest-dotnet](https://github.com/elastic/elastic-ingest-dotnet/blob/main/README.md)
* `Elastic.CommonSchema` was completely rearchitected as we rewritten the code generator from scratch to align with the ECS specification changes. 
  * `EcsDocument` now has an `AssignField(path, value)` method that can dynamically assign ECS fields based on `path`. This allows all the structured logging integrations to directly assign ECS fields too.
  * Through `CreateNewWithDefaults` all logging integrations share a common base default for how ecs documents get created and enriched.
* NLog integration has seen continued improvements from @snakefoot (Can't thank you enough for all your efforts!)
* Moved CI back onto Github Actions (thank you @v1v).


Breaking Changes.
* The root object for ECS documents in `Elastic.CommonSchema` was renamed from `Base` to `EcsDocument`.

**Comment by HubDevUser** [comment]
Can you please include .netstandard2.0 in the official 8.4.0 release. We need to consume this in fullframework, the alpha1 release only contains .netstandard2.1 assemblies

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz Are there plans to update documentation to show how to put all these together? For example, how to enhance the EcsDocument with custom fields.

**Comment by Mpdreamz** [comment]
@reydelleon-skuvault absolutely, docs are a big prerequisite for the 8.4.0-alpha release. 

I tried to capture some of the main differences between the sinks here for now: https://github.com/elastic/ecs-dotnet/tree/main/src/Elastic.CommonSchema.Serilog.Sink#comparison-with-serilogsinkselasticsearch

Any feedback or additional questions you may have are more than welcomed!

**Comment by Mpdreamz** [comment]
A quick extremely raw example of custom EcsDocument implementation is here: https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkDocument.cs#L16

**Comment by HubDevUser** [comment]
How can i set a custom index, it always defaults to ecs-dotnet-logs 
?

**Comment by HubDevUser** [comment]
Using aspnet core similar to the example you added earlier examples/aspnetcore-with-extensions-logging

**Comment by Mpdreamz** [comment]
> Using aspnet core similar to the example you added earlier examples/aspnetcore-with-extensions-logging

If you are using `Elasticsearch.Extensions.Logging` you can configure it in appsettings.json


```json
{
  "Logging": {
    "Elasticsearch": {
      "ShipTo": {
        "NodePoolType": "Static",
        "NodeUris": [ "http://localhost:9200" ]
      },
      "DataStream": {
        "DataSet": "my.application"
      }
    },
    "LogLevel" : {
      "Default": "Trace",
      "Microsoft": "Warning"
    }
  }
}

```

This will log to `logs-my.application-default`. 

You can also configure this in the application builder.

```csharp
builder.Host.ConfigureLogging((_, loggingBuilder) =>
{
	loggingBuilder.AddElasticsearch(opts =>
	{
		opts.DataStream = new DataStreamNameOptions
		{
			Type = "logs", DataSet = "dotnet", Namespace = "default"
		}
	}),
```

**Comment by Mpdreamz** [comment]
> Can you please include .netstandard2.0 in the official 8.4.0 release. We need to consume this in fullframework, the alpha1 release only contains .netstandard2.1 assemblies @Mpdreamz

I've just pushed `8.4.0-alpha2` with `netstandard2.0` support.

**Comment by HubDevUser** [comment]
It doesn't contain a .netstandard2.0 under libs, can you take a look please ?

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz I'm trying to use the new sink but I'm not seeing a way to specify auth credentials when configuring it. There is nothing about this in the README and looking through the code I wasn't able to identify a way to do this. 

Can you provide some guidance on this and perhaps add something in the examples in the README?

**Comment by lewinskimaciej** [comment]
@Mpdreamz I too can't seem to find a way of setting auth on new Serilog Elastic sink. I think this would be achievable by exposing setter ElasticsearchSinkOptions.Transport or some other, maybe nicer way. Currently it's always DefaultHttpTransport with default TransportConfiguration.

**Comment by HubDevUser** [comment]
@reydelleon-skuvault @lewinskimaciej  see https://github.com/elastic/ecs-dotnet/pull/267#discussion_r1107859406 for example on setting up the auth options

**Comment by HubDevUser** [comment]
@Mpdreamz how can we configure for .netfullframework where ILogger is not an option?

**Comment by LiorBanai** [comment]
@Mpdreamz you can use ILogger in net framework using the nuget:
```xml
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
```

**Comment by reydelleon-skuvault** [comment]
> @reydelleon-skuvault @lewinskimaciej see https://github.com/elastic/ecs-dotnet/pull/267#discussion_r1107859406 for example on setting up the auth options

@HubDevUser The example you linked is for the logging provider, not the sink. We need an example that works for the sink.

**Comment by Mpdreamz** [comment]
@reydelleon-skuvault thanks for bringing this to my attention I've opened https://github.com/elastic/ecs-dotnet/pull/286 to address this usability issue.

With that you should be able to use:

```sharp
.WriteTo.Elasticsearch(nodes, opts =>
{
	opts.BootstrapMethod = BootstrapMethod.Failure;
	opts.DataStream = new DataStreamName("logs", "console-example");

}, transport =>
{
	transport.Authentication();
})
```

**Comment by Mpdreamz** [comment]
I just pushed `8.4.0-alpha3` to nuget that includes netstandard2.0 for all projects and includes the fix to make it easier to configure the transport options when using the serilog sink.

Thanks everyone for kicking the tires!

**Comment by Mpdreamz** [comment]
I just pushed ECS.NET 8.4.0-alpha4 that includes everyones feedback and PR's much obliged to everyone kicking the tires!


I opened #291 to bump us to 8.6.0 and this includes some non breaking changes to how we bootstrap index templates. This PR will allow new version to upgrade template indices.

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz Is there a good way to see logs about the sink activity? I have SelfLog enabled for Serilog and the sink configured but thought I'm not getting any data in Elasticsearch, there is no indication as to what is the cause for this. Nothing written to the self log file (is it supposed to?). 

I have disabled pinging (a shot in the dark) but that didn't resolve it.

**Comment by Mpdreamz** [comment]
We are logging all export errors to Serilog's Self log: 

https://github.com/elastic/ecs-dotnet/blob/af53e3cdb8d00858b62f6d071b442163a9bfad9f/src/Elastic.CommonSchema.Serilog.Sink/ElasticsearchSink.cs#L77

The following diagnostics method is still ugly and not intended to make it to `1.0` but we ship with something called a `ChannelListener<>` if you do the following. 

```
	.WriteTo.Elasticsearch(....
    {
		ConfigureChannel = channelOpts =>  {
			channelOpts.BufferOptions = new BufferOptions { ExportMaxConcurrency = 10 };

			SomeStaticPlace = new ChannelListener<EcsDocument, BulkResponse>().Register(channelOpts);
		}
	})
```


What does `SomeStaticPlace.ToString()` report?

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz This is what I get from the code you posted:

```
Failed publish over channel: ChannelListener.
Exported Buffers: 0
Exported Items: 0
Export Responses: 0
Export Retries: 0
Export Exhausts: 0
Inbound Buffer Read Loop Started: False
Inbound Buffer Publishes: 0
Inbound Buffer Publish Failures: 0
Outbound Buffer Read Loop Started: False
Outbound Buffer Read Loop Exited: False
Outbound Buffer Publishes: 0
Outbound Buffer Publish Failures: 0

Exception: 
```
That's it. No more details than that. Here is my setup, in case I'm doing something wrong here:

```
loggerConfiguration
			.WriteTo.Elasticsearch<EnhancedEcsDocument>(
				new[] {new Uri("http://localhost:9200")},
				options =>
				{
					options.DataStream = new DataStreamName("logs", "myservice", environmentName.ToLowerInvariant());
					options.BootstrapMethod = BootstrapMethod.None ;
					};
				},
				transportConfig =>
					transportConfig
						.Authentication(new BasicAuthentication( "someUSer", "somePassword"))
						.DisablePing()
			);
```

**Comment by reydelleon-skuvault** [comment]
I ended up shipping the logs to a different Elasticsearch server, which means two things: 1. the problem was the server I was trying to ship to and 2. **The sink works as expected**. 

That said, I still don't know what the problem with the original server was because I didn't get anything in the Self log.

**Comment by Mpdreamz** [comment]
@reydelleon-skuvault Thanks for reporting back another instance works!

I would still love to improve the experience here and understand why the other instance does not work. 

Can you run the following in a new console application? Of course using 

```csharp
ChannelListener<EnhancedEcsDocument, BulkResponse>? listener = null;
var waitHandle = new CountdownEvent(1);

// -- Setup Serilog --
var nodes = new[] { new Uri("http://localhost:9200") };
Log.Logger = new LoggerConfiguration()
	.MinimumLevel.Debug()
	.MinimumLevel.Override("Microsoft", LogEventLevel.Information)
	.Enrich.FromLogContext()
	.WriteTo.Elasticsearch<EnhancedEcsDocument>(nodes, opts =>
	{
		opts.BootstrapMethod = BootstrapMethod.None;
		opts.DataStream = new DataStreamName("logs", "console-example");
		opts.ConfigureChannel = channelOpts => {
			channelOpts.BufferOptions = new BufferOptions
			{
				ExportMaxConcurrency = 1,
				OutboundBufferMaxSize = 2,
				WaitHandle = waitHandle
			};
			listener = new ChannelListener<EnhancedEcsDocument, BulkResponse>().Register(channelOpts);
		};
	}, 
	transportConfig =>
		transportConfig
			.Authentication(new BasicAuthentication( "someUSer", "somePassword"))
			.DisablePing()
    )
	.CreateLogger();

// -- Log 2 items and wait for flush --
Log.Logger.Information("Writing event 1");
Log.Logger.Information("Writing event 2");

if (!waitHandle.WaitHandle.WaitOne(TimeSpan.FromSeconds(10)))
	throw new Exception($"No flush occurred in 10 seconds: {listener}", listener?.ObservedException);
else
{
	Console.WriteLine("Successfully indexed data to Elasticsearch");
	Console.WriteLine(listener);
}
```

Thanks in advance!

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz This is what I get:

```
Successfully indexed data to Elasticsearch
Failed publish over channel: ChannelListener.
Exported Buffers: 1
Exported Items: 2
Export Responses: 1
Export Retries: 0
Export Exhausts: 0
Inbound Buffer Read Loop Started: True
Inbound Buffer Publishes: 2
Inbound Buffer Publish Failures: 0
Outbound Buffer Read Loop Started: True
Outbound Buffer Read Loop Exited: False
Outbound Buffer Publishes: 1
Outbound Buffer Publish Failures: 0

Exception: System.Exception: Unsuccessful () low level call on POST: /_bulk?filter_path=error%2C%20items.%2A.status%2Citems.%2A.error
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendi
ngRequestsCts, CancellationToken originalCancellationToken)
   at Elastic.Transport.HttpTransportClient.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---


Process finished with exit code 0.
```

Once more, I think the issue has to do with my server setup in this case. There seems to be more info here than in my previous attempt. For comparison, here is the output using a different server, where the credentials are wrong.

```
Exception: System.Exception: Unsuccessful (401) low level call on POST: /_bulk?filter_path=error%2C%20items.%2A.status%2Citems.%2A.error
 ---> Elastic.Transport.TransportException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration. Call: Status code 401 from: POST /_bulk?fil
ter_path=error%2C%20items.%2A.status%2Citems.%2A.error
 ---> Elastic.Transport.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
   at Elastic.Transport.DefaultRequestPipeline`1.ThrowBadAuthPipelineExceptionWhenNeeded(ApiCallDetails details, TransportResponse response)
   at Elastic.Transport.DefaultRequestPipeline`1.CallProductEndpointAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elastic.Transport.DefaultHttpTransport`1.RequestAsync[TResponse](HttpMethod method, String path, PostData data, RequestParameters requestParameters, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---

```

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz Is there documentation around SSL certificate configuration. What would be the best course of action if we're using a test Elasticsearch server (in Docker container, for example) that has a self signed certificate? Can I disable certificate validation on the sink for testing?

**Comment by reydelleon-skuvault** [comment]
@Mpdreamz I got another question about customizing the `EcsDocument`.

The examples I have found peppered in READMEs and tests all show contrived examples of how to subclass `EcsDocument` to introduce custom properties. They seem to suggest that you can do nesting (think the Contoso class with CompanyName as a nested property). In the `TryRead`, `ReceiveProperty` and `WriteAdditionalProperties` methods the examples show us handling the root property. Take this test for example: https://github.com/elastic/ecs-dotnet/blob/main/tests/Elastic.CommonSchema.Serilog.Tests/Repro/GithubIssue167.cs

Here is the `Tryread()` method for visibility:
```
protected override bool TryRead(string propertyName, out Type type)
{
	type = propertyName switch
	{
		"contoso" => typeof(Contoso),
		_ => null
	};
	return type != null;
}
```

The problem that I see with this is that I don't necessarily set the whole object in a `LogEvent` property. I might enrich the `LogEvent` with the `contoso.company_name` and set it to a single string value, but I will not set a `contoso` property in the `LogEvent` and set the value to the serialized contents of the object. 

I'm confused as to how all this should work (adding custom properties to `EcsDocument`). The benchmark example doesn't use Serilog. Is it that this only works when using the Elastic agent directly, without Serilog? Does it work with Serilog at all? Maybe I have to use the MapCustom function when working with Serilog and do the mapping myself?

Any guidance on this would be appreciated, since I need to add properties (not in metadata/labels).

**Comment by Mpdreamz** [comment]
> @Mpdreamz Is there documentation around SSL certificate configuration. What would be the best course of action if we're using a test Elasticsearch server (in Docker container, for example) that has a self signed certificate? Can I disable certificate validation on the sink for testing?

```csharp
.WriteTo.Elasticsearch(nodes, opts =>
{
	//
}, transport =>
{
	transport.ServerCertificateValidationCallback(CertificateValidations.AllowAll);
})
```
